

MIN_HULL_AREA_PERCENT = 0.05

MIN_POLY_POINTS = 3
MIN_HULL_POINTS = 3

MIN_ROTATED_BOX_AREA_PERCENT = 0.8
MIN_ROTATED_ELLIPSE_AREA_PERCENT = 0.6
MIN_POLY_AREA_PERCENT = 0.6

MAX_RATIO_SIZE = 3

MAX_GRAY_60_PERCENTILE = 175

MIN_VARIANCE = 10
