
# Do not use these params. Use instead conf
MIN_HULL_AREA_PERCENT_OF_MAX_HULL = 0.05
MIN_HULL_AREA_PERCENT_OF_IMG = 0.01

MIN_POLY_POINTS = 3
MIN_HULL_POINTS = 3

MIN_ROTATED_BOX_AREA_PERCENT = 0.8
MIN_ROTATED_ELLIPSE_AREA_PERCENT = 0.6
MIN_POLY_AREA_PERCENT = 0.6

MAX_RATIO_SIZE = 3

MAX_GRAY_60_PERCENTILE = 175

MIN_VARIANCE = 18

KEEP_PARTIAL = True


conf = {
        "THRESHOLD_BLOCK_SIZE_FACTOR": 50,
        "THRESHOLD_C": 5,

        "MIN_HULL_AREA_PERCENT_OF_MAX_HULL": 0.08,  # 0.15
        "MIN_HULL_AREA_PERCENT_OF_IMG": 0.01,

        "MIN_POLY_POINTS": 3,
        "MIN_HULL_POINTS": 3,

        "MIN_ROTATED_BOX_AREA_PERCENT": 0.8,
        "MIN_ROTATED_ELLIPSE_AREA_PERCENT": 0.4,
        "MIN_POLY_AREA_PERCENT": 0.6,

        "MAX_RATIO_SIZE": 3,

        "MAX_GRAY_60_PERCENTILE": 170,

        "MIN_VARIANCE": 18,

        "KEEP_PARTIAL": True
}
